services:
  - type: web
    name: fever-dream
    env: node
    region: oregon
    plan: free
    buildCommand: npm install --prefix server && npm install --prefix client && npm run build --prefix client
    startCommand: node server/src/index.js
    envVars:
      - key: NODE_ENV
        value: production
